from typing import Any
from datetime import datetime, timezone
from helpers import print_field, vt_verdict, ip_verdict, print_otx

def display_results(results: dict) -> None:
    
    print("=== Simple IOC Lookup v1.1.1 ===")
    if results.get("error"):
        print_field("Error:", results.get("error"))
    if results.get("type") == "hash":
        votes = results.get("total_votes", {})
        print("=== VirusTotal ===")
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        if results.get("error"):
            print_field("Verdict:", "N/A (VT lookup failed)")
        else:
            print_field("Verdict:", vt_verdict(results.get("malicious", 0), results.get("suspicious", 0)))
            print_field("Malicious: ", results.get("malicious"))
            print_field("Suspicious: ", results.get("suspicious"))
            print_field("Harmless: ", results.get("harmless"))
            print_field("Reputation: ", results.get("reputation"))
            print_field("Meaningful name: ", results.get("meaningful_name"))
            print_field("File Type: ", results.get("file_type"))
            print_field("Votes Malicious: ", votes.get("malicious", 0))
            print_field("Votes Harmless: ", votes.get("harmless", 0))
        print()
        print("=== OTX Threat Intelligence ===")
        print_otx(results)    
    elif results.get("type") == "url":
        votes = results.get("total_votes", {})
        whois = results.get("whois", {})
        org = whois.get("org")
        whois_created = whois.get("creation_date")
        whois_expiration = whois.get("expiration_date")
        print("=== VirusTotal ===")
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        if results.get("error"):
            print_field("Verdict:", "N/A (VT lookup failed)")
        else:
            print_field("Verdict:", vt_verdict(results.get("malicious", 0), results.get("suspicious", 0)))        
            print_field("Final URL: ", results.get("final_url"))
            if results.get("title"):
                print_field("Title: ", results.get("title"))
            print_field("Malicious: ", results.get("malicious"))
            print_field("Suspicious: ", results.get("suspicious"))
            print_field("Harmless: ", results.get("harmless"))
            print_field("Reputation: ", results.get("reputation"))
            print_field("Undetected: ", results.get("undetected"))
            print_field("Votes Malicious: ", votes.get("malicious", 0))
            print_field("Votes Harmless: ", votes.get("harmless", 0))
        print()
        print("=== WHOIS ===")
        print_field("Registrar (WHOIS): ", whois.get("registrar") or "Unknown")
        print_field("Org: ", org[0] if isinstance(org, list) else org or "Unknown")
        print_field("Country: ", whois.get("country") or "Unknown")        
        print_field("Created: ", whois_created.strftime('%Y-%m-%d') if whois_created else "Unknown")        
        print_field("Expires: ", whois_expiration.strftime('%Y-%m-%d') if whois_expiration else "Unknown")
        print_field("Name Servers: ", ", ".join(whois.get("name_servers", [])))   
        print()
        print("=== OTX Threat Intelligence ===")
        print_otx(results) 
    elif results.get("type") == "ip":
        print("=== AbuseIPDB ===")
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        print_field("Verdict:", ip_verdict(results.get("abuse_score", 0)))  
        if not results.get("error"):      
            print_field("Abuse Score: ", results.get("abuse_score"))
            print_field("Is Tor: ", results.get("is_tor"))
            print_field("Is Whitelisted: ", results.get("is_whitelisted"))
            print_field("Last Reported: ", results.get("last_reported"))
            print_field("Total Reports: ", results.get("total_reports"))
            print_field("Country: ", results.get("country"))
            print_field("ISP: ", results.get("isp"))
            print_field("Domain: ", results.get("domain"))    
        print()
        print("=== OTX Threat Intelligence ===")
        print_otx(results) 
    elif results.get("type") == "domain":
        votes = results.get("total_votes", {})
        vt_creation = results.get("creation_date")
        vt_expiration = results.get("expiration_date")
        whois = results.get("whois", {})
        org = whois.get("org")
        whois_created = whois.get("creation_date")
        whois_expiration = whois.get("expiration_date")
        print("=== VirusTotal ===")
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        if results.get("error"):
            print_field("Verdict:", "N/A (VT lookup failed)")
        else:
            print_field("Verdict:", vt_verdict(results.get("malicious", 0), results.get("suspicious", 0)))        
            print_field("Malicious: ", results.get("malicious"))
            print_field("Suspicious: ", results.get("suspicious"))
            print_field("Harmless: ", results.get("harmless"))
            print_field("Reputation: ", results.get("reputation"))
        print_field("Popularity Ranks: ", ", ".join(results.get("popularity_ranks", {}).keys()))
        print_field("Created (VT): ", datetime.fromtimestamp(vt_creation, tz=timezone.utc).strftime('%Y-%m-%d') if vt_creation else "Unknown")
        print_field("Expires (VT): ", datetime.fromtimestamp(vt_expiration, tz=timezone.utc).strftime('%Y-%m-%d') if vt_expiration else "Unknown")
        print_field("Categories: ", ", ".join(results.get("categories", {}).values()))    
        if not results.get("error"):    
            print_field("Votes Malicious: ", votes.get("malicious", 0))
            print_field("Votes Harmless: ", votes.get("harmless", 0))
        print()
        print("=== WHOIS ===")
        print_field("Registrar: ", results.get("registrar") or "Unknown")       
        print_field("Org: ", org[0] if isinstance(org, list) else org or "Unknown")
        print_field("Country: ", whois.get("country") or "Unknown")  
        print_field("Created (WHOIS): ", whois_created.strftime('%Y-%m-%d') if whois_created else "Unknown")
        print_field("Expires (WHOIS): ", whois_expiration.strftime('%Y-%m-%d') if whois_expiration else "Unknown")
        print_field("Registrar (WHOIS): ", whois.get("registrar") or "Unknown")
        print_field("Name Servers: ", ", ".join(whois.get("name_servers", [])))   
        print()
        print("=== OTX Threat Intelligence ===")
        print_otx(results)       
