from typing import Any
from datetime import datetime, timezone
from helpers import print_field, vt_verdict, ip_verdict

def display_results(results: dict) -> None:
    
    print("=== Simple IOC Lookup ===")
    if results.get("error"):
        print_field("Error: ", results.get("error"))
        return
    if results.get("type") == "hash":
        votes = results.get("total_votes", {})
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        print_field("Verdict: ", vt_verdict(results.get("malicious", 0), results.get("suspicious", 0)))
        print_field("Malicious: ", results.get("malicious"))
        print_field("Suspicious: ", results.get("suspicious"))
        print_field("Harmless: ", results.get("harmless"))
        print_field("Reputation: ", results.get("reputation"))
        print_field("Meaningful name: ", results.get("meaningful_name"))
        print_field("File Type: ", results.get("file_type"))
        print_field("Votes Malicious: ", votes.get("malicious", 0))
        print_field("Votes Harmless: ", votes.get("harmless", 0))        
    elif results.get("type") == "url":
        votes = results.get("total_votes", {})
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        print_field("Verdict:", vt_verdict(results.get("malicious", 0), results.get("suspicious", 0)))
        print_field("Final URL:", results.get("final_url"))
        print_field("Title:", results.get("title"))
        print_field("Malicious: ", results.get("malicious"))
        print_field("Suspicious: ", results.get("suspicious"))
        print_field("Harmless: ", results.get("harmless"))
        print_field("Reputation: ", results.get("reputation"))
        print_field("Undetected: ", results.get("undetected"))
        print_field("Votes Malicious: ", votes.get("malicious", 0))
        print_field("Votes Harmless: ", votes.get("harmless", 0)) 
        whois = results.get("whois", {})
        print_field("Registrar (WHOIS): ", whois.get("registrar", "Unknown"))
        org = whois.get("org")
        print_field("Org:", org[0] if isinstance(org, list) else org or "Unknown")
        print_field("Country: ", whois.get("country", "Unknown"))
        created = whois.get("creation_date")
        print_field("Created: ", created.strftime('%Y-%m-%d') if created else "Unknown")
        expiration = whois.get("expiration_date")
        print_field("Expires: ", expiration.strftime('%Y-%m-%d') if expiration else "Unknown")
        print_field("Name Servers: ", ", ".join(whois.get("name_servers", [])))      
    elif results.get("type") == "ip":
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        print_field("Verdict:", ip_verdict(results.get("abuse_score", 0)))
        print_field("Abuse Score: ", results.get("abuse_score"))
        print_field("Is Tor: ", results.get("is_tor"))
        print_field("Is Whitelisted: ", results.get("is_whitelisted"))
        print_field("Last Reported: ", results.get("last_reported"))
        print_field("Total Reports: ", results.get("total_reports"))
        print_field("Country: ", results.get("country"))
        print_field("ISP: ", results.get("isp"))
        print_field("Domain: ", results.get("domain"))     
    elif results.get("type") == "domain":
        votes = results.get("total_votes", {})
        creation = results.get("creation_date")
        expiration = results.get("expiration_date")
        print_field("IOC: ", results.get("ioc"))
        print_field("Type: ", results.get("type"))
        print_field("Verdict: ", vt_verdict(results.get("malicious", 0), results.get("suspicious", 0)))
        print_field("Malicious: ", results.get("malicious"))
        print_field("Suspicious: ", results.get("suspicious"))
        print_field("Harmless: ", results.get("harmless"))
        print_field("Reputation: ", results.get("reputation"))
        print_field("Registrar: ", results.get("registrar"))
        print_field("Created: ", datetime.fromtimestamp(creation, tz=timezone.utc).strftime('%Y-%m-%d') if creation else "Unknown")
        print_field("Expires: ", datetime.fromtimestamp(expiration, tz=timezone.utc).strftime('%Y-%m-%d') if expiration else "Unknown")
        print_field("Categories: ", ", ".join(results.get("categories", {}).values()))
        print_field("Popularity Ranks: ", ", ".join(results.get("popularity_ranks", {}).keys()))
        print_field("Votes Malicious: ", votes.get("malicious", 0))
        print_field("Votes Harmless: ", votes.get("harmless", 0))
        whois = results.get("whois", {})
        print_field("Registrar (WHOIS): ", whois.get("registrar", "Unknown"))
        org = whois.get("org")
        print_field("Org:", org[0] if isinstance(org, list) else org or "Unknown")
        print_field("Country: ", whois.get("country", "Unknown"))
        created = whois.get("creation_date")
        print_field("Created: ", created.strftime('%Y-%m-%d') if created else "Unknown")
        expiration = whois.get("expiration_date")
        print_field("Expires: ", expiration.strftime('%Y-%m-%d') if expiration else "Unknown")
        print_field("Name Servers: ", ", ".join(whois.get("name_servers", [])))
             
